### ISSUE TITLE
Latest release not compiling with Carthage

### ISSUE THREAD

**Issue by mmdumi** [urbanairship/ios-library#111]
For some reason carthage integration doesn't work any more.
Can you guys please have a look. 
Thanks

**Comment by rlepinski** [comment]
Yep, looking into now.

**Comment by rlepinski** [comment]
Could you post any build failure logs that you have?

**Comment by rlepinski** [comment]
Looks like carthage is hanging due to a bug in Xcode 8 https://forums.developer.apple.com/thread/50372. Its fixed in this commit - https://github.com/Carthage/Carthage/commit/12fb829fcedb90b50b26bac872e168653c7ddfe8 but is not released yet. Looking into providing prebuilt frameworks to workaround this issue.

**Comment by mmdumi** [comment]
Thank you!

**Comment by rlepinski** [comment]
I attached a binary to the 8.0.0 release. Could you see if that solves your problem?
