### ISSUE TITLE
Appdelegate method not called on iOS 10

### ISSUE THREAD

**Issue by rgmvisser** [urbanairship/ios-library#112]
I am running the library:
- Xcode 8
- iOS 10
- Automatic setup -> false

For iOS 9 the method `func application(application: UIApplication, didRegisterUserNotificationSettings notificationSettings: UIUserNotificationSettings) {` is called when I register for notifications. In the case of iOS 10 this is not the case. Can somebody confirm this?

**Comment by rlepinski** [comment]
Yeah, so didRegisterUserNotificationSettings is deprecated in iOS 10. Since you have disabled automatic setup, make sure you are forwarding the two [UNUserNotificationCenterDelegate](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate) methods to UAAppIntegration.

**Comment by rgmvisser** [comment]
It is deprecated, so it means that is still supported. I made a clean project with UA and the method is still called by iOS10, shouldn't UA also call this method then?

**Comment by rlepinski** [comment]
That method is only triggered if you use the deprecated registration flow. The Urban Airship SDK uses the new registration flow for iOS 10, so it will not trigger that method anymore. 

What are you trying to accomplish? Maybe we can work around your issue or provide a registration delegate method?

**Comment by rgmvisser** [comment]
We have some logic in that method that keeps track of the PN state of the user server side. I have now moved the logic to the delegate method where the device token is registered, this also seems to work.

**Comment by ShahriatHossain** [comment]
what should be the alternative of this method: didRegisterUserNotificationSettings 
for ios10?

**Comment by petarbelokonski** [comment]
didRegisterUserNotificationSettings is NOT deprecated in iOS 10, so the fact that it doesn't get called via UA is a mystery to me

**Comment by rlepinski** [comment]
Just so the response is also here:

@petarbelokonski Hmm, you are right that apple did not actually deprecate those methods. However they did UIUserNotificationSettings in favor of the new UNUserNotificaitonCenter calls. In order to trigger didRegisterUserNotificationSettings: you have to call registerUserNotificationSettings: with the deprecated class, so effectively that registration path is deprecated.

Our SDK calls the new UNUserNotificaitonCenter for iOS 10, so you will not get a call to didRegisterUserNotificationSettings:. We do provide several registration method callbacks that might be useful to you in our UAPushRegistrationDelegate. Specifically notificationRegistrationFinishedWithOptions:categories and
notificationAuthorizedOptionsDidChange: should be good replacements for didRegisterUserNotificationSettings: and they work across OS versions.

You should assign the push registration delegate immediately after takeOff:
```
// Swift
UAirship.push().registrationDelegate = customDelegate

// Obj-C
[UAirship push].registrationDelegate = customDelegate;
```

**Comment by petarbelokonski** [comment]
@rlepinski seems there is no difference in the parameters of the notificationRegistrationFinishedWithOptions:categories callback when the user taps on 'Allow' or 'Don't Allow'

**Comment by rlepinski** [comment]
It looks like notificationRegistrationFinishedWithOptions:categories: returns the app specified while notificationAuthorizedOptionsDidChange will return what you are looking for. I am out at a conference but someone from my team will look into the issue today.

**Comment by petarbelokonski** [comment]
@rlepinski `notificationAuthorizedOptionsDidChange` doesn't get called when you tap on "Don't Allow"
