### ISSUE TITLE
Possible un-intentional UA registration delegate callbacks every foreground event

### ISSUE THREAD

**Issue by JamesKuang** [urbanairship/ios-library#166]
We just updated our UA dependency and started noticing `UARegistrationDelegate`'s `registrationSucceeded(forChannelID channelID: String, deviceToken: String) ` is being called every time the app comes back into the foreground, which wasn't the case in the past. We believe it can be traced back to this commit ee7d288c5c4dfeeda2a2fc86c331f707b37ebc41.

We currently have code that fires a network call to register the device token to our platform upon this delegate callback. While we don't have a problem refactoring to account for his new behavior, I wanted to bring this up first, just in case it was not intentional. Because the documentation for this function says `Called when the device channel registers with Urban Airship.`, it seems odd that the device channel successfully registers with UA every time an app enters the foreground.

**Comment by BrianBatchelder** [comment]
This behavior changed with release 8.6.1. We now look for changes to notification authorization whenever the app is foregrounded.  If there are no changes, we simply update internal state and call the delegate's `registrationSucceededForChannelID` method, with the current channelID and deviceToken, which should be unchanged. That method has always been called even when there are no changes to the registration, it is now just called more often.

We'll update the documentation to indicate that `registrationSucceededForChannelID` may also be called even if SDK does not register with UA because the registration is unchanged.

**Comment by JamesKuang** [comment]
Sounds good, thanks.
