### ISSUE TITLE
UAChannelRegistrar.h file not found

### ISSUE THREAD

**Issue by walsht** [urbanairship/ios-library#176]
I am using Carthage to update Airship frameworks.  It was working fin in "9.0.4", but when I update to "9.1.0" it fails to compile.

Showing All Issues
<module-includes>:1:9: In file included from <module-includes>:1:
/Carthage/Build/iOS/AirshipKit.framework/Headers/AirshipKit.h:10:9: In file included from /Carthage/Build/iOS/AirshipKit.framework/Headers/AirshipKit.h:10:
/Carthage/Build/iOS/AirshipKit.framework/Headers/AirshipLib.h:27:9: 'UAChannelRegistrar.h' file not found
/NotificationManager.swift:10:8: Could not build Objective-C module 'AirshipKit'

![screen shot 2018-05-11 at 5 27 42 am](https://user-images.githubusercontent.com/1455799/39920374-81de2000-54dc-11e8-9b5e-d7b0656c6ed0.png)
![screen shot 2018-05-11 at 5 27 15 am](https://user-images.githubusercontent.com/1455799/39920375-81ec4f90-54dc-11e8-879b-edbc1f3ee2e0.png)
![screen shot 2018-05-11 at 5 26 56 am](https://user-images.githubusercontent.com/1455799/39920377-8202c39c-54dc-11e8-9ee0-f73045faedc0.png)

**Comment by crow** [comment]
Not sure off hand why this would occur looking at the project changes introduced in 9.1.0, will attempt to reproduce on a sample project, thanks for bringing this to our attention.

**Comment by crow** [comment]
I'm not able to reproduce this issue using the sample project. It's building fine after installing via Carthage. 

What does your framework search path look like?

If you look in "/Carthage/Build/iOS/AirshipKit.framework/Headers/" are you able to find UAChannelRegistar.h? If not, I would suggest rebuilding.

**Comment by walsht** [comment]
We are using static carthage frameworks.  https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md

Can you validate on the sample project that static Carthage frameworks works?

**Comment by crow** [comment]
sure can

**Comment by walsht** [comment]
Thank you.

**Comment by marc-scig** [comment]
Hi @walsht,

We made UAChannelRegistrar a framework-internal header recently, so it is no longer referenced in AirshipLib.h. My guess is you just have some old files from the previous framework versions that are hanging around. It might be worth cleaning/wiping that stuff, especially since static frameworks involve working from source. If the source is up to date, it should compile.

We will still be looking into our compatibility with static frameworks in the meanwhile, since this is new for us, so I'm going to leave this open for the moment. Let us know if you get it working, and we'll let you know our findings as well.

**Comment by marc-scig** [comment]
Quick update: I followed the instructions at https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md and it worked fine for me. However there a few things to keep in mind:

Since we use categories in our SDK, you will need to add -ObjC to "other linker flags" in your app's build settings, otherwise it will crash when the SDK tries to access those methods. Also, the normal AirshipKit.framework has additional resources in it such as XIBs and plists, that it requires to function properly. Since static frameworks are really just a convenient way of packaging a static library, these resources will no longer be available out of the box. But you can work around that by directly adding the AirshipResources.bundle to your project, which you should be able to find within the statically built AirshipKit.framework directory.

**Comment by walsht** [comment]
@marc-scig  Yes, you are right.  I had to completely remove the Carthage directory and rebuilding works fine.   Thank you.
