### ISSUE TITLE
Import without "enable modules" build setting

### ISSUE THREAD

**Issue by PhilipDukhov** [urbanairship/ios-library#190]
I've an old project, with a lot dependencies, and enabling modules makes it totally unbuildable.
To import Urbanairship I've cloned this repo (version 10.0.0), added AirshipKit.xcodeproj project to mine, added it to Embedded binaries. Also I've tried adding "path_to_repo/AirshipKit/AirshipKit/ios/" to HEADER_SEARCH_PATHS, and still I'm receiving 'AirshipKit/AirshipKit.h' file not found at this line:
#import <AirshipKit/AirshipKit.h>

Is there a way to build it without enabling modules?

**Comment by marc-scig** [comment]
Hi @PhilipDukhov,

You should be able to selectively turn off modules on your app's target and still use AirshipKit, you just won't be able to use the `@import` directive. However I doubt that AirshipKit.framework itself will build properly without modules support, at least not out of the box. Search paths aren't necessary when using frameworks so my guess is that if you're seeing that error you'll want to double check that the framework is properly added in an embedded binaries/linked frameworks and libraries. If everything checks out there, it's likely there's some other problem preventing the framework from building, which might explain why it's not finding the umbrella header.

As a last resort, we do also provide a static library, `libUAirship.a`, as well as a standalone resource bundle, `AirshipResources.bundle`, that you can use instead of AirshipKit. The easiest way to get this is as a direct download from bintray (https://bintray.com/urbanairship/iOS/download_file?file_path=urbanairship-sdk%2F10.0.0%2FlibUAirship-10.0.0.zip). If you go that route, that's when you'd want to set the header search paths to recursively include everything under the "Headers" directory, and then instead of `#import <AirshipKit/AirshipKit.h>` you'd instead use `#import AirshipLib.h`.

If you have any additional questions about this, please contact support.

best,
