### ISSUE TITLE
Why was matcherWithValueMatcher:key:valueMatcher deprecated and removed and what is the replacement method?

### ISSUE THREAD

**Issue by jjh8326** [urbanairship/ios-library#203]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
UA 10.0

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.
Xcode (no package manager)

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
We use the UAJSONMatcher method `matcherWithValueMatcher: key:valueMatcher` and now it is deprecated. It seems the replacement is `matcherWithValueMatcher:valueMatcher`. I am wondering why the new method removes the key and what happens to that key parameter and why is it not required and or are we supposed to supply that value somewhere else?

Example:
```
UAJSONMatcher *jsonMatcher = [UAJSONMatcher
                                  matcherWithValueMatcher: valueMatcher key: UACustomEventNameKey];
```
Above is how our application is currently handling this code, what is the 10 SDK way to handle this code?

**Comment by rlepinski** [comment]
The key is just the last part of the scope. It caused confusion within the team so we decided to deprecate and remove it since it did not really add value. The migration guide is light on the change probably because we thought only our sdk would actually use it. I'll make sure that gets updated with more info. For your example the replacement would be:
```
UAJSONMatcher *jsonMatcher = [UAJSONMatcher
                                  matcherWithValueMatcher: valueMatcher scope: @[UACustomEventNameKey]];
```

If you use scope and key, the key should be the last item in the scope array

**Comment by jjh8326** [comment]
Thank you for your well explained reply, I will update our code accordingly.
