### ISSUE TITLE
UAPush stores YES even if user doesn't allow

### ISSUE THREAD

**Issue by driley-emoney** [urbanairship/ios-library#217]
# Preliminary Info

### What Airship dependencies are you using?
Urban Airship iOS SDK 11.1.0

### What are the versions of any relevant development tools you are using?
XCode 10.3

# Report

### What unexpected behavior are you seeing?
When user notification prompt appears and user hits "Don't Allow", sdk stores YES so that it appears that notifications are enabled. 

### What is the expected behavior?
SDK should wait to see result of prompt and store YES or NO depending

### What are the steps to reproduce the unexpected behavior?
Request permission then hit Don't allow

### Do you have logging for the issue?
No logs, but the error is clear on this line:

https://github.com/urbanairship/ios-library/blob/7dd19c054fffa12c4ca3d63f1211c02ca96d8a40/AirshipKit/AirshipKit/common/UAPush.m#L347

**Comment by marc-scig** [comment]
Hi @driley-emoney,

`userPushNotificationsEnabled` is not directly related to whether the user has allowed them. When you set this property to `YES` (or `true` in Swift), it tells the SDK that it should prompt the user to authorize notifications. If it's `NO` or `false` the SDK won't even try, and notifications are effectively disabled regardless of the user's preferences. However, the user still has to authorize notifications for the channel to be considered opted-in, which is why we combine this property with the current authorization settings here, before registering with the backend: https://github.com/urbanairship/ios-library/blob/7dd19c054fffa12c4ca3d63f1211c02ca96d8a40/AirshipKit/AirshipKit/common/UAPush.m#L711)

**Comment by driley-emoney** [comment]
Thanks @marc-scig, so if I wanted to know if the user opted-in or opted-out previously, would I use authorizedNotificationSettings?

**Comment by shannon-livefront** [comment]
Is `userPushNotificationsAllowed` still the name of the relevant variable to use? I can't find that anywhere in the current SDK so wondered if it had been renamed?
