### ISSUE TITLE
Hard crash when setting UAirship.namedUser().identifier to nil

### ISSUE THREAD

**Issue by bofeizhu** [urbanairship/ios-library#228]
# Preliminary Info

### What Airship dependencies are you using?
12.0.0

### What are the versions of any relevant development tools you are using?
Xcode 11.1

# Report

### What unexpected behavior are you seeing?
Setting `UAirship.namedUser().identifier` to `nil` triggers hard crash. `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value.`

### What is the expected behavior?
No crash.

### What are the steps to reproduce the unexpected behavior?
Setting `UAirship.namedUser().identifier` to `nil`

### Do you have logging for the issue?
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

**Comment by bofeizhu** [comment]
I noticed that 

> * Initializes UAirship and performs all necessary setup. This creates the shared instance, loads
 * configuration values, initializes the analytics/reporting
 * module and creates a UAUser if one does not already exist.
 * 
 * This method *must* be called from your application delegate's
 * `application:didFinishLaunchingWithOptions:` method, and it may be called
 * only once.
 *
 * @warning `takeOff:` must be called on the main thread. This method will throw
 * an `UAirshipTakeOffMainThreadException` if it is run on a background thread.
 * @param config The populated UAConfig to use.
 *
 */
+ (void)takeOff:(nullable UAConfig *)config;

must be called in `application:didFinishLaunchingWithOptions:`. However, our app was setup in a way that the backend server is determined by the user's login status. Is there a way to change configuration after `application:didFinishLaunchingWithOptions:`?

**Comment by rlepinski** [comment]
Is the crash unwrapping UAirship.namedUser ? It's marked as null_unspecified because technically it can be nil, but after takeOff it is never nil. Sounds like for you, calling `UAirship.namedUser()?` will be safer.

Our SDK needs to be initialized early in the lifecycle to properly handle push notifications. My recommendation to you would be to delay takeOff the first run while you check with your backend, then after that call takeOff immediately in `application:didFinishLaunchingWithOptions:` so our SDK properly handles notifications. Still have your app check with your backend, and if the config changes, use that config the next time the app inits. All calls to `UAirship` should be treated as nullable during that first run.

**Comment by novinfard** [comment]
I don't think force unwrapping could be a good option regardless of how the framework has been setup in the project.
