### ISSUE TITLE
AirshipExtensions does not contain bitcode

### ISSUE THREAD

**Issue by vixez** [urbanairship/ios-library#252]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

`AirshipExtensions/NotificationService`

### What are the versions of any relevant development tools you are using?

Xcode 11.6
# Report

### What unexpected behavior are you seeing?

I'm using the Flutter SDK which is working fine by itself. The docs state:
```
To take advantage of notification attachments, such as images, animated gifs, and video, you will need to create a notification service extension.

Follow the CocoaPods steps in the iOS Notification Service Extension Guide.
```

So I follow the instructions, but it seems the SDK is not supported. Xcode shows the following error:

```
.../AirshipExtensions/AirshipExtensions.framework/AirshipExtensions' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../Xcode/DerivedData/Runner-cbmdpsbawkfvuzeirzrvwasynoni/Build/Products/Debug-iphoneos/AirshipExtensions/AirshipExtensions.framework/AirshipExtensions' for architecture arm64
```

### What is the expected behavior?

Working SDK when building with extensions.

### What are the steps to reproduce the unexpected behavior?

Follow the guide.

### Do you have logging for the issue?

```
.../AirshipExtensions/AirshipExtensions.framework/AirshipExtensions' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../Xcode/DerivedData/Runner-cbmdpsbawkfvuzeirzrvwasynoni/Build/Products/Debug-iphoneos/AirshipExtensions/AirshipExtensions.framework/AirshipExtensions' for architecture arm64
```

**Comment by marc-scig** [comment]
Hi @vixez,

Since this is a flutter SDK issue, in the future I'd appreciate it if you could bring similar questions to https://github.com/urbanairship/airship-flutter.

That said, Flutter doesn't enable bitcode by default, but bitcode is the default for new targets you create manually in Xcode (such as your app extension). If any target uses bitcode, then all of them have to use bitcode or else you'll encounter the error you're seeing during archival. So you have two options – if you don't care about bitcode support, just disable it in your app extension in Xcode by setting Enable Bitcode to NO, in Build Settings. If you do want bitcode, you can edit your app's Podfile to enable it for the rest of the targets, in the post_install hook at the bottom:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config| 
    config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
```
