### ISSUE TITLE
Message Center Inbox Count not updating when application is in Foreground

### ISSUE THREAD

**Issue by sridharsaminathn** [urbanairship/ios-library#278]
Hi, 

I want to update Message Center Inbox Unread count in Xamarin.iOS.
added Observer in NSNotificationCenter for getting the notifications.

`NSString UAMessageListUpdated = new NSString("com.urbanairship.notification.message_list_updated");
            NSNotificationCenter.DefaultCenter.AddObserver(UAMessageListUpdated, RefershBadgeCount);

 private void RefershBadgeCount(NSNotification obj)
        {
            var count = Airship.Instance.MessageCenterUnreadCount;
            //application.ApplicationIconBadgeNumber = count;
        }`

above method not triggering when the app receives a new message.

**Comment by marc-scig** [comment]
It looks like the line setting the badge number is commented out. Are you saying the method never gets triggered at all, or just not when you want it to?

How this works depends on what you're trying to accomplish. The message list updated notification gets triggered when the message list fetch completes, regardless of whether there was a new message or not. This will happen automatically when you transition to foreground, as well as when you pull to refresh the message center in the UI. But it's not directly tied to push notifications or the delivery of the inbox message on the backend.

**Comment by sridharsaminathn** [comment]
Method itseld not triggering, need to update the badge number in my application level when i push a message from backend

Updated Code

NSString UAMessageListUpdated = new NSString("com.urbanairship.notification.message_list_updated");
NSNotificationCenter.DefaultCenter.AddObserver(UAMessageListUpdated, RefershBadgeCount);

private void RefershBadgeCount(NSNotification obj)
{
var count = Airship.Instance.MessageCenterUnreadCount;
countLbl.Text = count;
}`

**Comment by marc-scig** [comment]
@sridharsaminathn I'm afraid that's not how the "com.urbanairship.notification.message_list_updated" notification works. I copied your code into our sample app and I'm seeing the method get triggered. However it won't trigger when the inbox is updated on the backend because there's no way for the SDK to know when that's happened. This notification fires when the _local_ contents of the inbox are updated, and that only happens when either the SDK or your app does a fetch. It's often used for updating UI state (such as a loading spinner).

I'm going to close this for now. Feel free to contact [support](https://support.airship.com/hc/en-us) if you need help with your particular use case.
