### ISSUE TITLE
README link to iOS Location documentation is a dead-link

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [urbanairship/ios-library#361]
# Preliminary Info

### What Airship dependencies are you using?
16.11.3

### What are the versions of any relevant development tools you are using?
N/A - README link issue

# Report

### What unexpected behavior are you seeing?
The location link in the README goes no where
https://docs.airship.com/platform/ios/location/

### What is the expected behavior?
The location link should point to documentation

### What are the steps to reproduce the unexpected behavior?
Click the link

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Fixed in 17.0.0. The location module is removed. You can use it in 16.x or replace it with a permissions delegate. I added in the migration guide for 17 but for 16 you need to convert it over to a completion handler instead of async function - https://github.com/urbanairship/ios-library/blob/main/Documentation/Migration/migration-guide-16-17.md#airshiplocation
