### ISSUE TITLE
Push shared instance not available for Objective C

### ISSUE THREAD

**Issue by BrandonStalnaker** [urbanairship/ios-library#404]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

    s.ios.dependency 'Airship', '~> 18.1'

### What are the versions of any relevant development tools you are using?

Xcode 15.3 
Cocaopods

# Report

### What unexpected behavior are you seeing?

When trying to call `UAirship.push` push is not being found as a object on UAirship.
<img width="1033" alt="Screenshot 2024-05-06 at 11 09 35 AM" src="https://github.com/urbanairship/ios-library/assets/33703490/0272f320-c13f-4f7f-b59d-c880ac1caade">

### What is the expected behavior?

Using the umbrella header in an objective C cocaopods workspace you should be able to access the push shared instance.

### What are the steps to reproduce the unexpected behavior?

Using the umbrella header in an objective C cocaopods workspace call any `UAirship.push` method.

**Comment by rlepinski** [comment]
It should be fixed in 18.1.1, could you verify the full version in your pod lock file? 

Not that this is the error you are encountering, but `updateRegistration` has been removed as well so you are going to want to remove that call. It should be handled for you now.

Another thing, we have identified an issue with coredata if you upgrade from 16.x (or older) to 18.x directly. If you are not coming from 17.x or newer, you may want to hold off til we get a patch out today or tomorrow.

**Comment by BrandonStalnaker** [comment]
@rlepinski  No I'm using 18.1.2 Here's my Podfile.lock
![image](https://github.com/urbanairship/ios-library/assets/33703490/032153b4-2281-41fa-9a7d-1f0ed6a4671a)

I think its cause its not marked public like analytics below it.
<img width="1109" alt="Screenshot 2024-05-07 at 10 18 02 AM" src="https://github.com/urbanairship/ios-library/assets/33703490/d96cb62c-3a25-463a-a806-b16ddfec980e">

**Comment by rlepinski** [comment]
🤦 Ill get it resolved with the patch going out today

**Comment by crow** [comment]
@BrandonStalnaker [Release 18.2.0](https://github.com/urbanairship/ios-library/releases/tag/18.2.0) is out with push exposed to obj-c
