### ISSUE TITLE
CoreData Migration issue

### ISSUE THREAD

**Issue by monishsyed** [urbanairship/ios-library#83]
After an upgrade from 4.x to 5.0 the content feed database is deleted because the core data model is incompatible. When a request to download the feed is made but a separate cache of already downloaded cards prevents this from succeeding.

**Comment by monishsyed** [comment]
Got a fix. Will have a PR for it soon. Thanks

**Comment by jkolb** [comment]
I have also seen this recently and found one other side effect from the lost database. Values can be left behind in NSUserDefaults (keys start with "UALastMessageListModifiedTime") that trigger an "If-Modified-Since" header to be sent to the server. When this header is sent to a production server after losing the database of messages the library will never be able to reload those lost messages. On a development server this issue is not noticed as the development server seems to ignore this header.

The code that triggers the header to be added to the request is in Airship/Inbox/UAInboxAPIClient.m

To work around both of these issues we had to clear the feed card disk cache and also remove all values from NSUserDefaults with the "UALastMessageListModifiedTime" key prefix.

**Comment by monishsyed** [comment]
@jkolb Yeah thats a issue we figured out a week ago. Seems like @rlepinski will have a fix for it in the next release.

**Comment by rlepinski** [comment]
Fixed with commit - f214dce643e625c3c570beba8d2127d504690192.
