### ISSUE TITLE
[UAInboxDBManager saveContext] crash

### ISSUE THREAD

**Issue by shrinivasa** [urbanairship/ios-library#87]
Please fix this crash 
![screen shot 2015-07-02 at 7 58 16 pm](https://cloud.githubusercontent.com/assets/1715795/8479414/4c1d7524-20f5-11e5-9e1b-25d13a6813c4.png)

**Comment by jtowle** [comment]
Thanks for the report! We request that all crash or bug reports be filed through support@urbanairship.com as our team doesn't actively monitor GitHub issues.

When you send the email, please include as much information as you can. In this case, make sure to include the Urban Airship SDK version(s) associated with the crash in your application. Since you are using Crashlytics, you can also share a copy of the full crash report with us. There is a "Share" button above the "Devices" graph (it's just cut off on the screenshot above). Clicking that reveals a link that you can send to our support team. Then just include any other info that would be useful, such a steps to reproduce if you've seen it during development.

Thanks again.
