### ISSUE TITLE
libUAirship has no armv7 bitcode

### ISSUE THREAD

**Issue by davepeck** [urbanairship/ios-library#89]
All apps and frameworks in bitcode-enabled projects _must_ themselves be bitcode enabled.

Looks like that's not (yet!) the case with `libUAirship`, at least for the `armv7` architecture. (And I assume `arm64` and `armv7s` as well?)

    ld: '.../UrbanAirship-iOS-SDK/Airship/libUAirship-6.1.2.a(UAWalletAction.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

**Comment by jtowle** [comment]
We'll be enabling that once we can start distributing a binary built with Xcode 7. Since the app store won't accept code from Xcode 7 at this point, we'd prefer it if people wanting to build a bitcode enabled binary do so from source.

Depending on what happens with the next betas, we may decide to include a not-for-distribution binary built with an Xcode 7 beta, but the best course of action for now is to build from source or disable bitcode in the app.

**Comment by davepeck** [comment]
Thanks @jtowle -- definitely makes sense. Do you have a quick pointer to instructions for building from source? Thanks.

**Comment by jtowle** [comment]
@davepeck There is a very brief mention in the README, but all you should need to do is edit `scripts/configure-xcode-version.sh` to point to either an environment variable or the path of your preferred Xcode version's .app bundle (e.g., `/Applications/Xcode7-beta4.app`), then run `Deploy/distribute.sh`. It will generate the zip file you would ordinarily download from our web site and print its location in the console.
